###################################################
#               Stage Declarations               #
###################################################
stages:
  - test

###################################################
#           Stage: test                           #
###################################################
testing-runner:
    stage: test
    only:
        - master
        - develop
    tags: 
        - teamhub
    script: '@Testing CI runner..'
